apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-jaeger-ui-frontend
  namespace: apps
spec:
  selector:
    matchLabels:
      app: solo-jaeger-ui-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: solo-jaeger-ui-frontend
    spec:
      containers:
        - name: solo-jaeger-ui-frontend
          image: $FRONTEND_IMAGE_NAME
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
